INSERT INTO EMPLOYEE(ID, NAME, SEX, HIREDATE) VALUES(1, 'BRIAN', 'MALE', PARSEDATETIME(CURRENT_TIMESTAMP(), 'yyyy-MM-dd hh:mm:ss'));
INSERT INTO EMPLOYEE(ID, NAME, SEX, HIREDATE) VALUES(2, 'ALLEN', 'FEMALE', PARSEDATETIME(CURRENT_TIMESTAMP(), 'yyyy-MM-dd hh:mm:ss'));
INSERT INTO EMPLOYEE(ID, NAME, SEX, HIREDATE) VALUES(3, 'DAVID', 'MALE', PARSEDATETIME(CURRENT_TIMESTAMP(), 'yyyy-MM-dd hh:mm:ss'));